### ISSUE TITLE
Discuss window size explicitly for rrs (and other families)

### ISSUE THREAD

**Issue by cole-miller** [zenhack/hashsplit-spec#4]
Using rrs as a rolling checksum (as opposed to hashing a fixed sequence of bytes) requires choosing a window size, which also appears in the definition of b(k, l) as l - k + 1. Of course applications may tweak this to suit their needs, but I think the spec would be clearer if it discussed window size explictly as a parameter for the rrs family -- or maybe once more hashes are covered there could be a general discussion of window size applying to all of them.

**Comment by zenhack** [comment]
Yeah, we definitely need to specify the window size somewhere, though as you point out this could be a hash-independent thing.

**Comment by zenhack** [comment]
This is in the spec now, so I'm going to close.
